[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Enable Next.js plugin for proper SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for Supabase
[context.production.environment]
  SUPABASE_URL = "https://tcmmloypcovltgciocdm.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjbW1sb3lwY292bHRnY2lvY2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzUyNDYsImV4cCI6MjA3MjY1MTI0Nn0.tbw_xiRAX34Vb71J3HhTZHLOpWQBueYg4t35HqD3J0U"